//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class product_DO_Entities2 : DbContext
    {
        public product_DO_Entities2()
            : base("name=product_DO_Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public virtual DbSet<Customers_Debt> Customers_Debt { get; set; }
        public virtual DbSet<Debit_supplier> Debit_supplier { get; set; }
        public virtual DbSet<PaymentCustomer> PaymentCustomer { get; set; }
        public virtual DbSet<PaymentSupplier> PaymentSupplier { get; set; }
        public virtual DbSet<TB_SUPLIERS> TB_SUPLIERS { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<TB_Users> TB_Users { get; set; }
    }
}
